# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.6"

matrix:
  include:
    - env: INTEGRATION=0 REDIS="redis==2.10.6"
    - env: INTEGRATION=0 REDIS="redis==3.1.0"
    - env: INTEGRATION=1 REDIS="redis"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q -r requirements-testing.txt
  - pip install -q $REDIS

# command to run tests
script: python setup.py nosetests -A integration==$INTEGRATION

services:
  - redis

notifications:
  email: false
  slack:
    rooms:
      - gadventures:IBz2ZsMXJpRjiT0OvZzYr7cp
    on_success: change
    on_failure: always
