# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.6"

sudo: false

env:
  - INTEGRATION=1
  - INTEGRATION=0

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-testing.txt
  - pip install redis

# command to run tests
script: python setup.py nosetests -A integration==$INTEGRATION

services:
  - redis

notifications:
  email: false
  slack:
    rooms:
      - gadventures:IBz2ZsMXJpRjiT0OvZzYr7cp
    on_success: change
    on_failure: always
