[tox]
envlist = py{311,312}
skip_missing_interpreters = True

[gh-actions]
# Note that this list of versions should correspond with what's in the GH workflow config
python =
    3.11: py311
    3.12: py312

[testenv]
commands =
    pip install -r requirements-testing.txt
    pytest -m "not integration" {env:PYTEST_ARGS:}
passenv = GAPI_APPLICATION_KEY PYTEST_ARGS
