# flake8: NOQA
from .tour import (
    Accommodation,
    Activity,
    CancellationTerm,
    Departure,
    DepartureComponent,
    Duration,
    FlexCancellationTerm,
    FlexPlan,
    FlexTier,
    Image,
    Itinerary,
    ItineraryHighlights,
    ItineraryMedia,
    Merchandise,
    OptionalActivity,
    Promotion,
    RegionalConnector,
    RoomUpgrade,
    SingleSupplement,
    Tour,
    TourCategory,
    TourDossier,
    Transport,
)

from .dossier import (
    AccommodationDossier,
    ActivityDossier,
    CountryDossier,
    DossierDetail,
    DossierDetailType,
    DossierFeature,
    DossierSegment,
    PlaceDossier,
    ServiceLevel,
    TransportDossier,
)

from .booking import (
    AccommodationService,
    ActivityService,
    Agency,
    AgencyChain,
    Agent,
    Booking,
    Checkin,
    Customer,
    DeclinedReason,
    DepartureService,
    Document,
    FeeService,
    FlexPlanService,
    FlexPlanServiceAddon,
    FlightService,
    InsuranceService,
    Invoice,
    MerchandiseService,
    Override,
    OverrideReason,
    Payment,
    Refund,
    RegionalConnectorService,
    Requirement,
    RequirementSet,
    RoomUpgradeService,
    ServiceCancellationTerm,
    SingleSupplementService,
    TransportService,
)

from .geo import (
    Airport,
    Continent,
    Country,
    Feature,
    FeatureCategory,
    Nationality,
    Place,
    State,
    Timezone,
)

from .booking_company import BookingCompany
from .language import Language


available_public_resources = [
    # Tour
    'Accommodation',
    'Activity',
    'CancellationTerm',
    'Departure',
    'DepartureComponent',
    'FlexCancellationTerm',
    'FlexPlan',
    'FlexTier',
    'Image',
    'Itinerary',
    'Merchandise',
    'OverrideReason',
    'Promotion',
    'RegionalConnector',
    'RoomUpgrade',
    'SingleSupplement',
    'Tour',
    'TourCategory',
    'TourDossier',
    'Transport',

    # Geographical
    'Airport',
    'Continent',
    'Country',
    'Feature',
    'FeatureCategory',
    'Place',
    'State',
    'Timezone',

    # Dossier
    'AccommodationDossier',
    'ActivityDossier',
    'CountryDossier',
    'DossierFeature',
    'DossierSegment',
    'Language',
    'PlaceDossier',
    'ServiceLevel',
    'TransportDossier',
]

available_private_resources = [
    'AccommodationService',
    'ActivityService',
    'Agency',
    'AgencyChain',
    'Agent',
    'Booking',
    'BookingCompany',
    'Checkin',
    'Customer',
    'DeclinedReason',
    'DepartureService',
    'Document',
    'FeeService',
    'FlexPlanService',
    'FlexPlanServiceAddon',
    'FlightService',
    'InsuranceService',
    'Invoice',
    'MerchandiseService',
    'Nationality',
    'Override',
    'Payment',
    'Refund',
    'Requirement',
    'RequirementSet',
    'RegionalConnectorService',
    'RoomUpgradeService',
    'ServiceCancellationTerm',
    'SingleSupplementService',
    'TransportService',
]

available_resources = available_public_resources + available_private_resources
